let firstName = "John";
let companyName = "Tech Solutions";
let mobileNumber = 9876543210;
let isAutomation = true;
let hasPlaywright;
console.log(firstName);
console.log(typeof firstName);
console.log(companyName);
console.log(typeof companyName);
console.log(mobileNumber);
console.log(typeof mobileNumber);
console.log(isAutomation);
console.log(typeof isAutomation);
console.log(hasPlaywright);
console.log(typeof hasPlaywright);